### ISSUE TITLE
打包后程序界面特别模糊

### ISSUE THREAD

**Issue by shiguanghuxian** [robertzhouxh/osx-dmg-maker#1]
![image](https://user-images.githubusercontent.com/13268627/60587647-8f50ca00-9dc7-11e9-82b4-80a95a9f6180.png)

**Comment by shiguanghuxian** [comment]
已解决
Info.plist文件加
  <key>NSHighResolutionCapable</key>
  <true/>

**Comment by robertzhouxh** [comment]
good
